name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install Wasp
              run: |
                  curl -sSL https://get.wasp.sh/installer.sh | sh
                  export PATH=$PATH:$HOME/.local/bin
                  echo "$HOME/.local/bin" >> $GITHUB_PATH

            - name: Code formatting check
              run: npx prettier --check .

            - name: TypeScript type check
              run: npx tsc --noEmit

            - name: Generate Prisma Client
              run: npx prisma generate
              env:
                  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"

            - name: Wasp build check
              run: wasp build

            - name: Database migration check
              run: wasp db migrate-dev --name ci-check
              env:
                  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
